name = "SPOD"
uuid = "0ac2d069-28cd-4d1e-aa57-4eb7242fcd6c"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
